# http://travis-ci.org/#!/GuoJing/Drop2Pi
language: python
python:
    - 2.6
    - 2.7
    - pypy
    - 3.2
    - 3.3

install:
    - python setup.py install
    - pip install watchdog
    - pip install dropbox
    - pip install pylint
    - pip install --use-mirrors coveralls

script:
    - pylint -E d2pi

after_success:
    coveralls