# http://travis-ci.org/#!/GuoJing/Drop2Pi

language: python
python:
    - 2.6
    - 2.7
    - pypy
    - 3.2
    - 3.3

install: "pip install -r requirements.txt"

script:
    - sh run_lint.sh
    - sh run_test.sh

after_success:
    coveralls