# http://travis-ci.org/#!/GuoJing/Drop2Pi

language: python
python:
    - 2.6
    - 2.7
    - pypy
    - 3.3
    - 3.4

install:
    - python setup.py install
    - pip install pytest
    - pip install mock
    - pip install watchdog
    - pip install dropbox
    - pip install pylint
    - pip install PyYAML
    - pip install --use-mirrors coveralls

script:
    - sh run_lint.sh
    - sh run_test.sh

after_success:
    coveralls
